### ISSUE TITLE
Npm Run Build fails to minify package

### ISSUE THREAD

**Issue by dylan-hoffmann** [johansatge/jpeg-autorotate#10]
Npm Run Build fro React apps fail to minify the code, likely (according to the README) because it wasn't precomiled to ES5

**Comment by johansatge** [comment]
Hi,

sorry, I didn't understand what the issue was. Do you have more details about your configuration and what you are trying to achieve?

Also, note the module currently doesn't work in the browser.

**Comment by johansatge** [comment]
Closing this. Please feel free to reopen if you reproduce the issue.
