### ISSUE TITLE
Rotation and flip bug?

### ISSUE THREAD

**Issue by dlednik** [johansatge/jpeg-autorotate#11]
I tried using this lib in nodejs project as I need to add images to PDF document. I had issues with images that had rotation defined in EXIF metadata. So I tested this lib with images from https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto

I used their images that are for testing in their git repo.

I see issues with orientations 5 and 7:
[EXIF_Content_A5_xmas.pdf](https://github.com/johansatge/jpeg-autorotate/files/2608317/EXIF_Content_A5_xmas.pdf)

How images are saved back to file once callback is called:
![image](https://user-images.githubusercontent.com/5610466/48907428-4c0ca100-ee5f-11e8-8879-cb3758cf6cb8.png)

**Comment by dlednik** [comment]
@johansatge any idea what is going on? I need fix for this asap and are willing to fix the source code my self if you give me some pointers where to start :+1:

**Comment by dlednik** [comment]
quick workaround if anyone needs it

```
if (orientation > 1) {
    if (orientation === 5 || orientation === 7) {
        // Until auto-rotate is fixed
        if (orientation === 5) {
            sharp(filePath).rotate(-90).flip().toBuffer().then( data => {
                fs.writeFileSync(filePath, data);
            }).catch( err => {
                Helper.returnError(res, err, 400, `api_v1_photo:get/${req.params.orderId}/${req.params.photoId}`);
            });
        } else {
            sharp(filePath).rotate(90).flip().toBuffer().then( data => {
                fs.writeFileSync(filePath, data);
            }).catch( err => {
                Helper.returnError(res, err, 400, `api_v1_photo:get/${req.params.orderId}/${req.params.photoId}`);
            });
        }
    } else {
        fs.writeFileSync(filePath, buffer);
    }
}
```

**Comment by johansatge** [comment]
Hi,

thanks a lot for reporting this.

I reproduce too with the images from the `/test/samples` directory. It looks like the issue has been here for some time, unfortunately.

I had a quick look in `src/transform.js` and didn't see what's wrong. I will analyze the issue deeper in the next days. Before next week hopefully.

_Note, this issue demonstrates that the existing tests are clearly not covering this module's features correctly. I have open #12 to try to fix this._
