### ISSUE TITLE
Wildcard support not working correctly in cli

### ISSUE THREAD

**Issue by joshuapeterson** [johansatge/jpeg-autorotate#19]
Wildcard and glob support in the CLI appears to be only reading the first file encountered.  If I have a directory with the following files:
* test1.jpg
* test2.jpg
* test3.jpg

and I run jpeg-autorotate test*.jpg, it will correctly process the first item and then no more.

**Comment by johansatge** [comment]
Thx for reporting this! Fixed in `5.0.3`.
