### ISSUE TITLE
Glob as CLI path

### ISSUE THREAD

**Issue by Tiliavir** [johansatge/jpeg-autorotate#2]
Maybe I'm just missing something to get it right, but it seems like the tool does not support glob paths am I right there? I tried the following:

```
jpeg-autorotate input/**/*.{jpg,jpeg,JPG,JPEG}
```

but keep getting:

```
> jpeg-autorotate input/**/*.{jpg,jpeg,JPG,JPEG}

input/**/*.{jpg,jpeg,JPG,JPEG}: Could not read file (ENOENT: no such file or directory,
open 'C:\Test\input\**\*.{jpg,jpeg,JPG,JPEG}')
```

What am I doing wrong? Hints are very welcome ;-)

**Comment by johansatge** [comment]
Hi,

_Sorry for the delay, vacations with no internet_ 😉 

You are right, currently I don't use `glob` with the CLI mode. Seems like a good idea, I will try to have a look at this in the next days/weeks. (unless you want to do it and submit a PR?)

Thanks!

**Comment by johansatge** [comment]
It looks like the _next days/weeks_ have become the _next months_ 😊  time flies.

I have added `glob` support in `jpg-autorotate@3.0.0` (see commit [007c401](https://github.com/johansatge/jpeg-autorotate/commit/007c4016d2b0165d5eb8d1452e2bbbb764ada7e5)).
