### ISSUE TITLE
is quality 100 the same as lossless?

### ISSUE THREAD

**Issue by Offirmo** [johansatge/jpeg-autorotate#23]
This module looks awesome and I'd like to use it to sort my billion photos.

However, I'm concerned in the loss of quality in my pictures. I know that the JPG format allows lossless rotation (https://www.betterjpeg.com/lossless-rotation.htm)

Is it what your module does? Or does your module rotate the full bit plane then re-encode?

**Comment by johansatge** [comment]
Hi,

the rotation will not be lossless unfortunately, no matter the selected quality.

If you configure `quality: 100` you will probably end up with a bigger image than the original (this is a [known issue with `jpeg-js`](https://github.com/eugeneware/jpeg-js/issues/45), the decoder/encoder used in this project.)

If you plan on using the tool on a big number of images, I can only encourage you to make backups and try different qualities to find the more relevant one for your use case :)

**Comment by Offirmo** [comment]
Thanks for the answer.

I couldn't find a lossless rotate on npm so far, will keep looking.
