### ISSUE TITLE
Ability to increase the maxMemoryUsageInMB option in jpeg-autorotate

### ISSUE THREAD

**Issue by Stompf** [johansatge/jpeg-autorotate#26]
We sometimes have images that needs more then the default 512 MB of memory that is set by the maxMemoryUsageInMB option for jpeg-js (https://github.com/eugeneware/jpeg-js#decode-options). It would be awesome if we could increase this value as an option to this module so we can use this module even for bigger images.

**Comment by johansatge** [comment]
Hi, thanks for your feedback 👍

I didn't notice `jpeg.decode()` accepts options; I'll update the module so users can set them (Update coming in the next hours)

**Comment by johansatge** [comment]
Done in `7.1.0` with the new `jpegjsMaxResolutionInMP` & `jpegjsMaxMemoryUsageInMB` options.

**Comment by Stompf** [comment]
Thanks for the quick update! Seems to work good :)
