### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by nobody0702** [johansatge/jpeg-autorotate#3]
jpeg-autorotate upload/20170220204242-image.jpg

upload/20170220204242-image.jpg: EACCES: permission denied, open 'upload/20170220204242-image.jpg'

I don't want to use sudo. Any Idea?

**Comment by johansatge** [comment]
Hi,

are you sure you have the permissions to modify `upload/20170220204242-image.jpg`?

`jpeg-autorotate` doesn't require `sudo` to work.

**Comment by nobody0702** [comment]
Yes， actually.  It is a problem of permission. I've solved it. thank you !
