### ISSUE TITLE
CLI unusable due to "colors" module debacle

### ISSUE THREAD

**Issue by CherryDT** [johansatge/jpeg-autorotate#33]
![image](https://user-images.githubusercontent.com/6010463/148794656-53d51990-2eb1-499f-b5ad-f35ca158b788.png)

This is because the `colors` library is allowed to be updated to 1.4.1/1.4.2, introducing [this mess](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/).

Pinning it to `1.4.0` should fix it for now. Consider switching to an alternative.

**Comment by johansatge** [comment]
Hey, thanks for reporting this! I forgot this project was relying on `colors`; I will publish a new version that don't rely on it later today.

**Comment by johansatge** [comment]
Fixed in #34 / `jpeg-autorotate@8.0.1`.

Thanks again!
